name: Update Cloudflare Images
on:
  schedule:
    - cron: "*/30 * * * *"
  label:
    types: [created]

defaults:
  run:
    working-directory: minimal-cf-images

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          # cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Pamp it
        env: # Or as an environment variable
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        run: |
          python main.py